# Generated by Django 4.2 on 2025-02-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
