# Generated by Django 4.2 on 2025-02-18 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_road_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('small', 'Light Vehicle'), ('big', 'Heavy Vehicle')], max_length=10)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White')], max_length=10)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('load_volume', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.person')),
            ],
        ),
        migrations.RemoveField(
            model_name='lightvehicle',
            name='owner',
        ),
        migrations.AlterField(
            model_name='tollstation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HeavyVehicle',
        ),
        migrations.DeleteModel(
            name='LightVehicle',
        ),
    ]
