# Generated by Django 4.2 on 2025-02-22 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_remove_lightvehicle_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
